name: Site
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
      
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "17"
        
      - name: mkdir
        run: |
          mkdir -p build/static
          mkdir -p build/site
      
      - name: Get Template
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "J-Cake/jstempl"
          file: "template-standalone.cjs"
          target: "build/template.js"

      - name: Build
        run: |
          node ./build.mjs pages

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: dothething.jschneiderprojects.com.au 
          username: dothething
          key: ${{ secrets.JSCHNEIDERPROJECTS_DEPLOY_KEY }}
          source: "build/site/"
          target: "/var/www/dothething"