name: Site
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
      
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "17"
        
      - name: mkdir
        run: |
          mkdir -p build/static
          mkdir -p build/site
      
      - name: Get Template
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "J-Cake/jstempl"
          file: "template-standalone.cjs"
          target: "build/template.js"

      - name: Build
        run: |
          node build.mjs pages
          cp assets build/site

      - name: Deploy
        uses: nogsantos/scp-deploy@master
        with:
          src: build/site
          host: jschneiderprojects.com.au
          remote: /var/www/dothething
          port: 22
          user: dothething
          key: ${{ secrets.SSH_KEY }}